-- Olympian Fitness / Supabase
-- Ejecutar en el SQL Editor de Supabase.

create extension if not exists pgcrypto;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  nombre varchar(30) unique not null
);

insert into public.roles (id, nombre) values
  (1, 'admin'), (2, 'entrenador'), (3, 'usuario')
on conflict (id) do update set nombre = excluded.nombre;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre_completo varchar(150) not null,
  correo varchar(150) unique not null,
  telefono varchar(30),
  rol_id bigint not null references public.roles(id) default 3,
  activo boolean not null default true,
  fecha_registro timestamptz not null default now()
);

create table if not exists public.entrenadores (
  id bigint generated by default as identity primary key,
  usuario_id uuid unique not null references public.usuarios(id) on delete cascade,
  especialidad varchar(150) not null,
  descripcion text
);

create table if not exists public.planes (
  id bigint generated by default as identity primary key,
  nombre varchar(100) not null,
  precio numeric(10,2) not null,
  beneficios text not null,
  destacado boolean not null default false
);

create table if not exists public.membresias (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  plan_id bigint not null references public.planes(id),
  fecha_inicio date not null,
  fecha_fin date not null,
  estado varchar(20) not null default 'activa' check (estado in ('activa','vencida','cancelada')),
  metodo_pago varchar(30) not null default 'efectivo',
  referencia_pago varchar(100),
  detalle_pago varchar(150)
);

create table if not exists public.citas (
  id bigint generated by default as identity primary key,
  entrenador_id bigint not null references public.entrenadores(id) on delete cascade,
  cliente_id uuid references public.usuarios(id) on delete set null,
  fecha date not null,
  hora_inicio time not null,
  hora_fin time not null,
  estado varchar(20) not null default 'disponible' check (estado in ('disponible','confirmado','cancelado'))
);

create table if not exists public.horario_gimnasio (
  id bigint generated by default as identity primary key,
  dias varchar(100) not null,
  apertura time not null,
  cierre time not null,
  telefono varchar(30)
);

create table if not exists public.rutinas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  entrenador_id bigint references public.entrenadores(id) on delete set null,
  nombre varchar(150) not null,
  duracion_min integer,
  descripcion text,
  fecha_creacion timestamptz not null default now()
);

create table if not exists public.rutina_ejercicios (
  id bigint generated by default as identity primary key,
  rutina_id bigint not null references public.rutinas(id) on delete cascade,
  dia varchar(30) not null,
  ejercicio varchar(150) not null,
  series integer,
  repeticiones varchar(30),
  notas varchar(200),
  orden integer not null default 0
);

create table if not exists public.foro_temas (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  titulo varchar(200) not null,
  contenido text not null,
  fecha_creacion timestamptz not null default now()
);

create table if not exists public.foro_respuestas (
  id bigint generated by default as identity primary key,
  tema_id bigint not null references public.foro_temas(id) on delete cascade,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  contenido text not null,
  fecha_creacion timestamptz not null default now()
);

create table if not exists public.historial_asistencias (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios(id) on delete cascade,
  fecha date not null,
  hora_entrada time not null,
  hora_salida time,
  actividad varchar(100) not null
);

insert into public.planes (id, nombre, precio, beneficios, destacado) values
(1, 'PLAN BÁSICO', 50000, 'Acceso al gimnasio\nUso de máquinas', false),
(2, 'PLAN PREMIUM', 120000, 'Todo Incluido\nEntrenador Personal', true),
(3, 'PLAN VIP', 80000, 'Clases Grupales\nAcceso a todo el Gimnasio', false)
on conflict (id) do update set
  nombre=excluded.nombre, precio=excluded.precio, beneficios=excluded.beneficios, destacado=excluded.destacado;

insert into public.horario_gimnasio (id, dias, apertura, cierre, telefono) values
(1, 'Lunes a Miércoles', '03:00', '23:00', '3205000000'),
(2, 'Jueves a Viernes', '02:00', '12:00', '3205000000'),
(3, 'Sábados, domingos y festivos', '00:00', '23:59', '3205000000')
on conflict (id) do update set
  dias=excluded.dias, apertura=excluded.apertura, cierre=excluded.cierre, telefono=excluded.telefono;

-- Perfil automático al registrarse con Supabase Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.usuarios (id, nombre_completo, correo, telefono, rol_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombre_completo', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data->>'telefono',
    3
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Funciones auxiliares de autorización.
create or replace function public.mi_rol()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select r.nombre
  from public.usuarios u
  join public.roles r on r.id = u.rol_id
  where u.id = auth.uid()
$$;

alter table public.usuarios enable row level security;
alter table public.entrenadores enable row level security;
alter table public.planes enable row level security;
alter table public.membresias enable row level security;
alter table public.citas enable row level security;
alter table public.horario_gimnasio enable row level security;
alter table public.rutinas enable row level security;
alter table public.rutina_ejercicios enable row level security;
alter table public.foro_temas enable row level security;
alter table public.foro_respuestas enable row level security;
alter table public.historial_asistencias enable row level security;

-- Políticas básicas para el frontend.
create policy "usuarios leen su perfil" on public.usuarios
for select using (id = auth.uid() or public.mi_rol() = 'admin');

create policy "usuario actualiza su perfil" on public.usuarios
for update using (id = auth.uid() or public.mi_rol() = 'admin');

create policy "planes visibles" on public.planes
for select using (true);

create policy "horarios visibles" on public.horario_gimnasio
for select using (true);

create policy "entrenadores visibles" on public.entrenadores
for select using (true);

create policy "clientes ven sus membresias" on public.membresias
for select using (usuario_id = auth.uid() or public.mi_rol() = 'admin');

create policy "clientes crean membresia" on public.membresias
for insert with check (usuario_id = auth.uid());

create policy "rutinas visibles al dueño" on public.rutinas
for select using (
  usuario_id = auth.uid()
  or public.mi_rol() in ('admin','entrenador')
);

create policy "ejercicios visibles" on public.rutina_ejercicios
for select using (
  exists (
    select 1 from public.rutinas r
    where r.id = rutina_id
      and (r.usuario_id = auth.uid() or public.mi_rol() in ('admin','entrenador'))
  )
);

create policy "foro temas visibles" on public.foro_temas
for select using (true);

create policy "usuarios crean temas" on public.foro_temas
for insert with check (usuario_id = auth.uid());

create policy "foro respuestas visibles" on public.foro_respuestas
for select using (true);

create policy "usuarios responden" on public.foro_respuestas
for insert with check (usuario_id = auth.uid());

create policy "asistencias propias" on public.historial_asistencias
for select using (usuario_id = auth.uid() or public.mi_rol() = 'admin');

-- El resto de políticas administrativas/agenda se puede endurecer después
-- de validar los flujos del proyecto.
